/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RiskMatrixRouteImport } from './routes/risk-matrix'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWhoDonRouteImport } from './routes/api/who-don'

const RiskMatrixRoute = RiskMatrixRouteImport.update({
  id: '/risk-matrix',
  path: '/risk-matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhoDonRoute = ApiWhoDonRouteImport.update({
  id: '/api/who-don',
  path: '/api/who-don',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/risk-matrix': typeof RiskMatrixRoute
  '/api/who-don': typeof ApiWhoDonRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/risk-matrix': typeof RiskMatrixRoute
  '/api/who-don': typeof ApiWhoDonRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/risk-matrix': typeof RiskMatrixRoute
  '/api/who-don': typeof ApiWhoDonRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/risk-matrix' | '/api/who-don'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/risk-matrix' | '/api/who-don'
  id: '__root__' | '/' | '/risk-matrix' | '/api/who-don'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RiskMatrixRoute: typeof RiskMatrixRoute
  ApiWhoDonRoute: typeof ApiWhoDonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/risk-matrix': {
      id: '/risk-matrix'
      path: '/risk-matrix'
      fullPath: '/risk-matrix'
      preLoaderRoute: typeof RiskMatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/who-don': {
      id: '/api/who-don'
      path: '/api/who-don'
      fullPath: '/api/who-don'
      preLoaderRoute: typeof ApiWhoDonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RiskMatrixRoute: RiskMatrixRoute,
  ApiWhoDonRoute: ApiWhoDonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
